kraut_api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from kraut_api import views

urlpatterns = [
    # indicators
    url(r'^indicators/$', views.indicator_list),
    url(r'^indicators/(?P<pk>[0-9]+)/$', views.indicator_detail),
    url(r'^indicators/(?P<pk>[0-9]+)/related/$', views.indicator_detail_related_indicators),
    url(r'^indicators/(?P<pk>[0-9]+)/ttps/$', views.indicator_detail_ttps),
    url(r'^indicators/(?P<pk>[0-9]+)/observables/$', views.indicator_detail_observables),
    url(r'^indicators/(?P<pk>[0-9]+)/compositions/$', views.indicator_detail_compositions),
    # observables
    url(r'^observables/$', views.observable_list),
    url(r'^observables/(?P<pk>[0-9]+)/$', views.observable_detail),
    url(r'^observables/(?P<pk>[0-9]+)/related_objects/$', views.observable_related_objects),
    url(r'^observables/(?P<pk>[0-9]+)/related_packages/$', views.observable_related_packages),
    url(r'^observables/(?P<pk>[0-9]+)/related_indicators/$', views.observable_related_indicators),
    # malware instances
    url(r'^malware_instances/$', views.malware_instances_list),
    # attack pattern
    url(r'^attack_patterns/$', views.attack_patterns_list),
    # campaign
    url(r'^campaigns/$', views.campaign_list),
    url(r'^campaigns/(?P<pk>[0-9]+)/$', views.campaign_detail),
    url(r'^campaigns/(?P<pk>[0-9]+)/related/$', views.campaign_detail_related_indicators),
    url(r'^campaigns/(?P<pk>[0-9]+)/associated/$', views.campaign_detail_associated_campaigns),
    url(r'^campaigns/(?P<pk>[0-9]+)/related_ttps/$', views.campaign_detail_related_ttps),
    url(r'^campaigns/(?P<pk>[0-9]+)/related_packages/$', views.campaign_detail_related_packages),
    # threat actor
    url(r'^threatactors/$', views.threatactor_list),
    url(r'^threatactors/(?P<pk>[0-9]+)/$', views.threatactor_detail),
    url(r'^threatactors/(?P<pk>[0-9]+)/associated/$', views.threatactor_detail_associated_threatactors),
    url(r'^threatactors/(?P<pk>[0-9]+)/campaigns/$', views.threatactor_detail_campaigns),
    url(r'^threatactors/(?P<pk>[0-9]+)/related_packages/$', views.threatactor_detail_related_packages),
    url(r'^threatactors/(?P<pk>[0-9]+)/observed_ttps/$', views.threatactor_detail_observed_ttps),
    # package
    url(r'^packages/$', views.package_list),
    url(r'^packages/(?P<pk>[0-9]+)/$', views.package_detail),
    url(r'^packages/(?P<pk>[0-9]+)/observables/$', views.package_detail_observables),
    url(r'^packages/(?P<pk>[0-9]+)/indicators/$', views.package_detail_indicators),
    url(r'^packages/(?P<pk>[0-9]+)/campaigns/$', views.package_detail_campaigns),
    url(r'^packages/(?P<pk>[0-9]+)/threatactors/$', views.package_detail_threatactors),
    url(r'^packages/(?P<pk>[0-9]+)/ttps/$', views.package_detail_ttps),
    url(r'^packages/(?P<pk>[0-9]+)/quick/(?P<otype>[a-zA-Z]+)/$', views.package_quick, name="package_quick"),
    url(r'^packagesd3/tree/(?P<pk>[0-9]+)/$', views.package_tree),
    # objects
    url(r'^objects/(?P<object_id>[0-9]+)/(?P<object_type>[a-zA-Z0-9]+)/packages/$', views.object_get_packages),
    url(r'^objects/(?P<object_id>[0-9]+)/(?P<object_type>[a-zA-Z0-9]+)/observables/$', views.object_get_observables),
    url(r'^objects/hashes/$', views.object_hash_list),
    url(r'^objects/ips/$', views.object_ip_list),
    url(r'^objects/domains/$', views.object_domain_list),
    url(r'^compositions/(?P<pk>[0-9]+)/$', views.composition_details),
    url(r'^compositions/(?P<pk>[0-9]+)/d3/$', views.composition_details_d3),
    # incident
    url(r'^incident/contacts/$', views.contact_list),
    url(r'^incident/handlers/$', views.handler_list),
    url(r'^incident/tasks/$', views.template_tasks),
    url(r'^incident/(?P<incident_id>[0-9]+)/handlers/$', views.handler_list_incident),
    url(r'^incident/(?P<incident_id>[0-9]+)/contacts/$', views.contact_list_incident),
    url(r'^incidents/$', views.incident_list),
    # ttp
    url(r'^ttps/$', views.ttp_list),
    url(r'^ttp/(?P<pk>[0-9]+)/related_ttps/$', views.ttp_related_ttps),
    url(r'^ttp/(?P<pk>[0-9]+)/related_packages/$', views.ttp_related_packages),
    url(r'^ttp/(?P<pk>[0-9]+)/malware_instances/$', views.ttp_malware_instances),
    url(r'^ttp/(?P<pk>[0-9]+)/attack_patterns/$', views.ttp_attack_patterns),
    # taxii
    url(r'^taxii/feed/information/$', views.taxii_feed_information),
    url(r'^taxii/servers/$', views.taxii_server_list),
    url(r'^taxii/collections/$', views.taxii_collection_list),
    url(r'^comments/(?P<object_type>[a-zA-Z0-9]+)/$', views.list_comments),
]

urlpatterns = format_suffix_patterns(urlpatterns)

kraut_base/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from kraut_base import views

app_name = 'kraut_base'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^incidents/', include(('kraut_incident.urls', 'incidents'), namespace='incidents')),
    url(r'^intel/', include(('kraut_intel.urls', 'intel'), namespace='intel')),
    url(r'^sharing/', include(('kraut_sharing.urls', 'sharing'), namespace='sharing')),
    url(r'^export/', include(('kraut_export.urls', 'export'), namespace='export')),
    url(r'^accounts/', include(('kraut_accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^api/', include(('kraut_api.urls', 'api'), namespace='api')),
    url(r'^api-auth/', include(('rest_framework.urls', 'rest_framework'), namespace='rest_framework')),
    url(r'^search/', include(('kraut_search.urls', 'search'), namespace='search')),
    url(r'^admin/', admin.site.urls),
]

kraut_intel/urls.py
from django.conf.urls import url
from kraut_intel import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    # packages
    url(r'^packages/$', views.packages, name='packages'),
    url(r'^package/(?P<package_id>\d+)/$', views.package, name='package'),
    url(r'^package/(?P<package_id>\d+)/graph/$', views.package_graph, name='package_graph'),
    url(r'^package/(?P<package_id>\d+)/delete/$', views.delete_package, name='delete_package'),
    url(r'^package/(?P<package_id>\d+)/update/header$', views.update_package_header, name='update_package_header'),
    url(r'^package/(?P<package_id>\d+)/edit/$', views.edit_create_package, name='edit_create_package'),
    url(r'^package/(?P<package_id>\d+)/add/(?P<item_id>\d+)/(?P<item_name>\w+)/$', views.add_item_to_package, name='add_item_to_package'),
    url(r'^package/(?P<package_id>\d+)/add/comment$', views.comment_package, name='comment_package'),
    url(r'^package/(?P<package_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_package, name='delete_comment_package'),
    # threat actors
    url(r'^threatactors/$', views.threatactors, name='threatactors'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/$', views.threatactor, name='threatactor'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/delete/$', views.delete_threatactor, name='delete_threatactor'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/edit/$', views.edit_create_threatactor, name='edit_create_threatactor'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/update/header$', views.update_ta_header, name='update_ta_header'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/add/comment$', views.comment_actor, name='comment_actor'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_actor, name='delete_comment_actor'),
    # campaigns
    url(r'^campaigns/$', views.campaigns, name='campaigns'),
    url(r'^campaign/(?P<campaign_id>\d+)/$', views.campaign, name='campaign'),
    url(r'^campaign/(?P<campaign_id>\d+)/delete/$', views.delete_campaign, name='delete_campaign'),
    url(r'^campaign/(?P<campaign_id>\d+)/add/comment$', views.comment_campaign, name='comment_campaign'),
    url(r'^campaign/(?P<campaign_id>\d+)/update/header$', views.update_campaign_header, name='update_campaign_header'),
    url(r'^campaign/(?P<campaign_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_campaign, name='delete_comment_campaign'),
    # ttps
    url(r'^ttps/$', views.ttps, name='ttps'),
    url(r'^ttp/(?P<ttp_id>\d+)/$', views.ttp, name='ttp'),
    url(r'^ttp/(?P<ttp_id>\d+)/delete/$', views.delete_ttp, name='delete_ttp'),
    url(r'^ttp/(?P<ttp_id>\d+)/add/comment$', views.comment_ttp, name='comment_ttp'),
    url(r'^ttp/(?P<ttp_id>\d+)/update/header$', views.update_ttp_header, name='update_ttp_header'),
    url(r'^ttp/(?P<ttp_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_ttp, name='delete_comment_ttp'),
    # indicators
    url(r'^indicators/$', views.indicators, name='indicators'),
    url(r'^indicator/(?P<indicator_id>\d+)/$', views.indicator, name='indicator'),
    url(r'^indicator/(?P<indicator_id>\d+)/update/header$', views.update_indicator_header, name='update_indicator_header'),
    url(r'^indicator/(?P<indicator_id>\d+)/delete/$', views.delete_indicator, name='delete_indicator'),
    url(r'^indicator/(?P<indicator_id>\d+)/add/comment$', views.comment_indicator, name='comment_indicator'),
    url(r'^indicator/(?P<indicator_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_indicator, name='delete_comment_indicator'),
    # observables
    url(r'^observables/$', views.observables, name='observables'),
    url(r'^observable/(?P<observable_id>\d+)/$', views.observable, name='observable'),
    url(r'^observable/(?P<observable_id>\d+)/update/header$', views.update_observable_header, name='update_observable_header'),
    url(r'^observable/(?P<observable_id>\d+)/delete/$', views.delete_observable, name='delete_observable'),
    url(r'^observable/(?P<observable_id>\d+)/add/comment$', views.comment_observable, name='comment_observable'),
    url(r'^observable/(?P<observable_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_observable, name='delete_comment_observable'),
    # malware instance
    url(r'^mwinstances/$', views.malware_instances, name='malware_instances'),
    url(r'^mwinstance/(?P<mwi_id>\d+)/$', views.malware_instance, name='malware_instance'),
    url(r'^mwinstance/(?P<mwi_id>\d+)/delete/$', views.delete_malware_instance, name='delete_malware_instance'),
    url(r'^mwinstance/(?P<mwi_id>\d+)/update/header$', views.update_mwinstance_header, name='update_mwinstance_header'),
    # attack pattern
    url(r'^attpatterns/$', views.attack_patterns, name='attack_patterns'),
    url(r'^attpattern/(?P<ap_id>\d+)/$', views.attack_pattern, name='attack_pattern'),
    url(r'^mwinstance/(?P<ap_id>\d+)/delete/$', views.delete_attack_pattern, name='delete_attack_pattern'),
    url(r'^attpattern/(?P<ap_id>\d+)/update/header$', views.update_attpattern_header, name='update_attpattern_header'),
]

kraut_base/views.py
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

from django.shortcuts import render
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.templatetags.static import static

from kraut_intel.utils import get_icon_for_namespace

from kraut_parser.models import Package, ThreatActor, Campaign, Indicator, Observable, TTP

# Create your views here.

@login_required
def home(request):
    context = {'indicators': 0, 'observables': 0, 'campaigns': 0, 'threatactors': 0, 'packages': 0}
    context['packages'] = Package.objects.count()
    context['threatactors'] = ThreatActor.objects.count()
    context['campaigns'] = Campaign.objects.count()
    context['ttps'] = TTP.objects.count()
    context['indicators'] = Indicator.objects.count()
    context['observables'] = Observable.objects.count()
    if hasattr(request.user.userextension, 'namespaces'):
        context['usernamespace'] = request.user.userextension.namespaces.last().namespace.split(':')[0]
        context['namespaceicon'] = get_icon_for_namespace(request.user.userextension.namespaces.last().namespace)
    else:
        context['usernamespace'] = 'nospace'
        context['namespaceicon'] = static('ns_icon/octalpus.png')
    return render(request, 'kraut_base/index.html', context)

kraut_base/templates/kraut_base/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block sidebar %}
{% spaceless %}
<div class="page-header">
    <div class="media">
        <div class="media-left">
            <img src="{{ namespaceicon}}" height="64" class="media-object">
        </div>
        <div class="media-body">
            <h2 class="media-heading" data-toggle="tooltip" data-placement="left" data-original-title="My initial namespace">{{ usernamespace }}</h2>Side Panel
        </div>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Statistics
            <i class="fa fa-question-circle fa-sm" data-container="body" data-toggle="popover" data-placement="right" data-content="This table shows the total number of database entries for each of the different threat intelligence types. (Intelligence Package, Threat Actors, Campaigns, Indicators, and Observables)"></i>
        </h3>
    </div>
    <div class="panel-body">
        <table class="table table-condensed table-borderless">
            <tbody>
                <tr>
                    <td align="center"><h1>{{ packages }}</h1><a href="{% url 'intel:packages' %}">Intelligence Packages</a></td>
                </tr>
                <tr>
                    <td align="center"><h1>{{ threatactors }}</h1><a href="{% url 'intel:threatactors' %}">Threat Actors</a></td>
                </tr>
                <tr>
                    <td align="center"><h1>{{ campaigns }}</h1><a href="{% url 'intel:campaigns' %}">Campaigns</a></td>
                </tr>
                <tr>
                    <td align="center"><h1>{{ ttps }}</h1><a href="{% url 'intel:ttps' %}">Tools, Tactics, and Procedures</a></td>
                </tr>
                <tr>
                    <td align="center"><h1>{{ indicators }}</h1><a href="{% url 'intel:indicators' %}">Indicators</a></td>
                </tr>
                <tr>
                    <td align="center"><h1>{{ observables }}</h1><a href="{% url 'intel:observables' %}">Observables</a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endspaceless%}
{% endblock %}

{% block content %}
{% spaceless %}
<div class="page-header">
    <div class="media">
        <div class="media-left">
            <img src="{% static 'images/Kraut.svg' %}" height="64" class="media-object" />
        </div>
        <div class="media-body">
            <h2 class="media-heading">Kraut Base</h2>observe items that recently changed or were added ...
        </div>
    </div>
</div>
{% if messages %}{% for message in messages %}<div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>{% endfor %}{% endif %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Recent URIs</h3>
    </div>
    <div class="panel-body">
        <div role="tabpanel">
        <table id="uri_table" class="table table-condensed table-striped table-bordered" style="font-size: 0.9em;">
            <thead>
                <tr>
                    <th>URI</th>
                    <th>Type</th>
                    <th>Operations</th>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        </div>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Recent IP Addresses</h3>
    </div>
    <div class="panel-body">
        <div role="tabpanel">
        <table id="ip_table" class="table table-condensed table-striped table-bordered" style="font-size: 0.9em;">
            <thead>
                <tr>
                    <th>IP Address</th>
                    <th>Category</th>
                    <th>Operations</th>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        </div>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Recent Hashes</h3>
    </div>
    <div class="panel-body">
        <div role="tabpanel">
        <table id="hash_table" class="table table-condensed table-striped table-bordered" style="font-size: 0.9em;">
            <thead>
                <tr>
                    <th>MD5 Hash</th>
                    <th>SHA256 Hash</th>
                    <th>Operations</th>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        </div>
    </div>
</div>


<!-- Hashes Modal -->
<div class="modal fade" id="hashesModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Select Observable</h4>
            </div>
            <div class="modal-body">
                <table id="hash_observable_table" class="table table-condensed table-striped table-bordered" style="font-size: 0.9em;">
                    <thead>
                        <th>ID</th>
                        <th>Name</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endspaceless%}
{% endblock%}

{% block javascript %}
<script type="text/javascript" language="javascript" class="init">
$(function () {
    $('[data-toggle="popover"]').popover()
});


$('#hashesModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var objectid = button.data('objectid') // Extract info from data-* attributes
  var category = button.data('cat')
  var modal = $(this)
  modal.find('.modal-title').text('Select Observable for Object ID: ' + objectid)
  var HashObservableTable = $('#hash_observable_table').DataTable({
    ordering: false,
    paging: false,
    info: false,
    filter: false,
    processing: true,
    serverSide: true,
    bLengthChange: false,
    oLanguage: {
      sProcessing: "<img src='{% static 'images/loading.gif' %}'>",
    },
    ajax: {
      processing: true,
      url: "/api/objects/"+objectid+"/"+category+"/observables/",
      dataSrc: "results",
      type: "GET",
      dataType: "json"
    },
    columns: [
      {'data': 'id', 'sName': 'ID', 'aTargets': [ 1 ]},
      {
        'data': 'name', 
        'sName': 'Name', 
        'aTargets': [ 2 ],
        'mRender': function (data, type, full) {
            var view_url = "{% url 'intel:observable' observable_id=0 %}".replace(0, Number(full.id));
            return '<a href="'+view_url+'">'+data+'</a>';
        }
      },
    ],
  });
  HashObservableTable.destroy();
});

$(document).ready( function () {
    var HashTable = $('#hash_table').DataTable({
        processing: true,
        serverSide: true,
        bLengthChange: false,
        oLanguage: {
            sProcessing: "<img src='{% static 'images/loading.gif' %}'>",
        },
        ajax: {
            processing: true,
            url: "/api/objects/hashes/",
            dataSrc: "results",
            type: "GET",
            dataType: "json"
        },
        columns: [
            {'data': 'md5_hash', 'sName': 'MD5 Hash', 'aTargets': [ 1 ]},
            {'data': 'sha256_hash', 'sName': 'SHA256 Hash', 'aTargets': [ 2 ]},
            {
                'data': 'id',
                'sName': 'operations',
                'bSortable': false,
                'aTargets': [ 3 ],
                "mRender": function (data, type, full) {
                    return '<div class="btn-group1">' +
                        '<a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View" href="#" data-toggle="modal" data-target="#hashesModal" data-objectid="'+data+'" data-cat="FileObjectType">' +
                        '<i class="fa fa-eye"></i>' +
                        '</a>' +
                        '</div>';
                },
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    $("a", nTd).tooltip();
                }
            }
        ],
    });
});

$(document).ready( function () {
    var IPTable = $('#ip_table').DataTable({
        processing: true,
        serverSide: true,
        bLengthChange: false,
        oLanguage: {
            sProcessing: "<img src='{% static 'images/loading.gif' %}'>",
        },
        ajax: {
            processing: true,
            url: "/api/objects/ips/",
            dataSrc: "results",
            type: "GET",
            dataType: "json"
        },
        columns: [
            {'data': 'address_value', 'sName': 'IP Address', 'aTargets': [ 1 ]},
            {'data': 'category', 'sName': 'Category', 'aTargets': [ 2 ]},
            {
                'data': 'id',
                'sName': 'operations',
                'bSortable': false,
                'aTargets': [ 3 ],
                "mRender": function (data, type, full) {
                    return '<div class="btn-group1">' +
                        '<a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View" href="#" data-toggle="modal" data-target="#hashesModal" data-objectid="'+data+'" data-cat="AddressObjectType">' +
                        '<i class="fa fa-eye"></i>' +
                        '</a>' +
                        '</div>';
                },
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    $("a", nTd).tooltip();
                }
            }
        ],
    });
});


$(document).ready( function () {
    var URITable = $('#uri_table').DataTable({
        processing: true,
        serverSide: true,
        bLengthChange: false,
        oLanguage: {
            sProcessing: "<img src='{% static 'images/loading.gif' %}'>",
        },
        ajax: {
            processing: true,
            url: "/api/objects/domains/",
            dataSrc: "results",
            type: "GET",
            dataType: "json"
        },
        columns: [
            {
                'data': 'short_value',
                'sName': 'URI', 
                'aTargets': [ 1 ],
                "mRender": function (data, type, full) {
                    return '<div rel="tooltip" data-placement="top" data-original-title="'+full.uri_value+'">'+data+'</div>';
                },
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    $("div", nTd).tooltip();
                },
            },
            {'data': 'uri_type', 'sName': 'URI Type', 'aTargets': [ 2 ]},
            {
                'data': 'id',
                'sName': 'operations',
                'bSortable': false,
                'aTargets': [ 3 ],
                "mRender": function (data, type, full) {
                    return '<div class="btn-group1">' +
                        '<a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View" href="#" data-toggle="modal" data-target="#hashesModal" data-objectid="'+data+'" data-cat="URIObjectType">' +
                        '<i class="fa fa-eye"></i>' +
                        '</a>' +
                        '</div>';
                },
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    $("a", nTd).tooltip();
                }
            }
        ],
    });
});

$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock%}