kraut_api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from kraut_api import views

urlpatterns = [
    # indicators
    url(r'^indicators/$', views.indicator_list),
    url(r'^indicators/(?P<pk>[0-9]+)/$', views.indicator_detail),
    url(r'^indicators/(?P<pk>[0-9]+)/related/$', views.indicator_detail_related_indicators),
    url(r'^indicators/(?P<pk>[0-9]+)/ttps/$', views.indicator_detail_ttps),
    url(r'^indicators/(?P<pk>[0-9]+)/observables/$', views.indicator_detail_observables),
    url(r'^indicators/(?P<pk>[0-9]+)/compositions/$', views.indicator_detail_compositions),
    # observables
    url(r'^observables/$', views.observable_list),
    url(r'^observables/(?P<pk>[0-9]+)/$', views.observable_detail),
    url(r'^observables/(?P<pk>[0-9]+)/related_objects/$', views.observable_related_objects),
    url(r'^observables/(?P<pk>[0-9]+)/related_packages/$', views.observable_related_packages),
    url(r'^observables/(?P<pk>[0-9]+)/related_indicators/$', views.observable_related_indicators),
    # malware instances
    url(r'^malware_instances/$', views.malware_instances_list),
    # attack pattern
    url(r'^attack_patterns/$', views.attack_patterns_list),
    # campaign
    url(r'^campaigns/$', views.campaign_list),
    url(r'^campaigns/(?P<pk>[0-9]+)/$', views.campaign_detail),
    url(r'^campaigns/(?P<pk>[0-9]+)/related/$', views.campaign_detail_related_indicators),
    url(r'^campaigns/(?P<pk>[0-9]+)/associated/$', views.campaign_detail_associated_campaigns),
    url(r'^campaigns/(?P<pk>[0-9]+)/related_ttps/$', views.campaign_detail_related_ttps),
    url(r'^campaigns/(?P<pk>[0-9]+)/related_packages/$', views.campaign_detail_related_packages),
    # threat actor
    url(r'^threatactors/$', views.threatactor_list),
    url(r'^threatactors/(?P<pk>[0-9]+)/$', views.threatactor_detail),
    url(r'^threatactors/(?P<pk>[0-9]+)/associated/$', views.threatactor_detail_associated_threatactors),
    url(r'^threatactors/(?P<pk>[0-9]+)/campaigns/$', views.threatactor_detail_campaigns),
    url(r'^threatactors/(?P<pk>[0-9]+)/related_packages/$', views.threatactor_detail_related_packages),
    url(r'^threatactors/(?P<pk>[0-9]+)/observed_ttps/$', views.threatactor_detail_observed_ttps),
    # package
    url(r'^packages/$', views.package_list),
    url(r'^packages/(?P<pk>[0-9]+)/$', views.package_detail),
    url(r'^packages/(?P<pk>[0-9]+)/observables/$', views.package_detail_observables),
    url(r'^packages/(?P<pk>[0-9]+)/indicators/$', views.package_detail_indicators),
    url(r'^packages/(?P<pk>[0-9]+)/campaigns/$', views.package_detail_campaigns),
    url(r'^packages/(?P<pk>[0-9]+)/threatactors/$', views.package_detail_threatactors),
    url(r'^packages/(?P<pk>[0-9]+)/ttps/$', views.package_detail_ttps),
    url(r'^packages/(?P<pk>[0-9]+)/quick/(?P<otype>[a-zA-Z]+)/$', views.package_quick, name="package_quick"),
    url(r'^packagesd3/tree/(?P<pk>[0-9]+)/$', views.package_tree),
    # objects
    url(r'^objects/(?P<object_id>[0-9]+)/(?P<object_type>[a-zA-Z0-9]+)/packages/$', views.object_get_packages),
    url(r'^objects/(?P<object_id>[0-9]+)/(?P<object_type>[a-zA-Z0-9]+)/observables/$', views.object_get_observables),
    url(r'^objects/hashes/$', views.object_hash_list),
    url(r'^objects/ips/$', views.object_ip_list),
    url(r'^objects/domains/$', views.object_domain_list),
    url(r'^compositions/(?P<pk>[0-9]+)/$', views.composition_details),
    url(r'^compositions/(?P<pk>[0-9]+)/d3/$', views.composition_details_d3),
    # incident
    url(r'^incident/contacts/$', views.contact_list),
    url(r'^incident/handlers/$', views.handler_list),
    url(r'^incident/tasks/$', views.template_tasks),
    url(r'^incident/(?P<incident_id>[0-9]+)/handlers/$', views.handler_list_incident),
    url(r'^incident/(?P<incident_id>[0-9]+)/contacts/$', views.contact_list_incident),
    url(r'^incidents/$', views.incident_list),
    # ttp
    url(r'^ttps/$', views.ttp_list),
    url(r'^ttp/(?P<pk>[0-9]+)/related_ttps/$', views.ttp_related_ttps),
    url(r'^ttp/(?P<pk>[0-9]+)/related_packages/$', views.ttp_related_packages),
    url(r'^ttp/(?P<pk>[0-9]+)/malware_instances/$', views.ttp_malware_instances),
    url(r'^ttp/(?P<pk>[0-9]+)/attack_patterns/$', views.ttp_attack_patterns),
    # taxii
    url(r'^taxii/feed/information/$', views.taxii_feed_information),
    url(r'^taxii/servers/$', views.taxii_server_list),
    url(r'^taxii/collections/$', views.taxii_collection_list),
    url(r'^comments/(?P<object_type>[a-zA-Z0-9]+)/$', views.list_comments),
]

urlpatterns = format_suffix_patterns(urlpatterns)

kraut_base/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from kraut_base import views

app_name = 'kraut_base'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^incidents/', include(('kraut_incident.urls', 'incidents'), namespace='incidents')),
    url(r'^intel/', include(('kraut_intel.urls', 'intel'), namespace='intel')),
    url(r'^sharing/', include(('kraut_sharing.urls', 'sharing'), namespace='sharing')),
    url(r'^export/', include(('kraut_export.urls', 'export'), namespace='export')),
    url(r'^accounts/', include(('kraut_accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^api/', include(('kraut_api.urls', 'api'), namespace='api')),
    url(r'^api-auth/', include(('rest_framework.urls', 'rest_framework'), namespace='rest_framework')),
    url(r'^search/', include(('kraut_search.urls', 'search'), namespace='search')),
    url(r'^admin/', admin.site.urls),
]

kraut_incident/urls.py
from django.conf.urls import url
from kraut_incident import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^list/$', views.list_incidents, name='list'),
    url(r'^new/$', views.new_incident, name='new'),
    url(r'^incident/(?P<incident_id>\d+)/delete/$', views.delete_incident, name='delete_incident'),
    url(r'^incident/(?P<incident_id>\d+)/view/$', views.view_incident, name='view_incident'),
    url(r'^incident/(?P<incident_id>\d+)/close/$', views.close_incident, name='close_incident'),
    url(r'^incident/(?P<incident_id>\d+)/update/header/$', views.update_incident_header, name='update_incident_header'),
    url(r'^incident/(?P<incident_id>\d+)/add/task/$', views.add_task, name='add_task'),
    url(r'^incident/(?P<incident_id>\d+)/add/handler/$', views.add_handler_incident, name='add_handler_incident'),
    url(r'^incident/(?P<incident_id>\d+)/add/contact/$', views.add_contact_incident, name='add_contact_incident'),
    url(r'^incident/(?P<incident_id>\d+)/remove/handler/(?P<handler_id>\d+)/$', views.remove_handler_incident, name='remove_handler_incident'),
    url(r'^incident/(?P<incident_id>\d+)/remove/contact/(?P<contact_id>\d+)/$', views.remove_contact_incident, name='remove_contact_incident'),
    url(r'^incident/(?P<incident_id>\d+)/remove/task/(?P<task_id>\d+)/$', views.remove_task_incident, name='remove_task_incident'),
    url(r'^incident/(?P<incident_id>\d+)/resolve/task/(?P<task_id>\d+)/$', views.resolve_task_incident, name='resolve_task_incident'),
    url(r'^incident/(?P<incident_id>\d+)/abort/task/(?P<task_id>\d+)/$', views.abort_task_incident, name='abort_task_incident'),
    url(r'^incident/(?P<incident_id>\d+)/add/comment/$', views.comment_incident, name='comment_incident'),
    url(r'^incident/(?P<incident_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_incident, name='delete_comment_incident'),
    url(r'^create_contact/$', views.create_contact, name='create_contact'),
    url(r'^create_handler/$', views.create_handler, name='create_handler'),
]

kraut_incident/views.py
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

import json

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import render
from django.template import RequestContext
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from kraut_intel.utils import get_icon_for_namespace

from kraut_incident.forms import IncidentForm, ContactForm, HandlerForm, IncidentCommentForm
from kraut_incident.models import Contact, Handler, Incident, IncidentComment, TemplateTask, Task, Incident_Status
from kraut_incident.utils import slicedict

import datetime

# Create your views here.

@login_required
def home(request):
    context = {}
    return render(request, 'kraut_incident/index.html', context)

@login_required
def list_incidents(request):
    context = {}
    return render(request, 'kraut_incident/incident_list.html', context)

@login_required
def abort_task_incident(request, incident_id, task_id):
    """abort a task from an incident
    """
    context = {}
    try:
        inc = Incident.objects.get(id=incident_id)
    except Incident.DoesNotExist:
        messages.error(request, 'The requested incident does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    try:
        task = Task.objects.get(id=task_id)
    except Task.DoesNotExist:
        messages.error(request, 'The requested task does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    task.status = 'ab'
    task.finish_time = datetime.datetime.now()
    task.save()
    return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))

@login_required
def resolve_task_incident(request, incident_id, task_id):
    """resolve a task from an incident
    """
    context = {}
    try:
        inc = Incident.objects.get(id=incident_id)
    except Incident.DoesNotExist:
        messages.error(request, 'The requested incident does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    try:
        task = Task.objects.get(id=task_id)
    except Task.DoesNotExist:
        messages.error(request, 'The requested task does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    task.status = 'do'
    task.finish_time = datetime.datetime.now()
    task.save()
    return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))

@login_required
def remove_task_incident(request, incident_id, task_id):
    """remove a task from an incident
    """
    context = {}
    try:
        inc = Incident.objects.get(id=incident_id)
    except Incident.DoesNotExist:
        messages.error(request, 'The requested incident does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    try:
        task = Task.objects.get(id=task_id)
    except Task.DoesNotExist:
        messages.error(request, 'The requested task does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    inc.tasks.remove(task)
    inc.save()
    return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))

@login_required
def remove_contact_incident(request, incident_id, contact_id):
    """remove contact person from incident
    """
    context = {}
    try:
        inc = Incident.objects.get(id=incident_id)
    except Incident.DoesNotExist:
        messages.error(request, 'The requested incident does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    try:
        contact = Contact.objects.get(id=contact_id)
    except Handler.DoesNotExist:
        messages.error(request, 'The requested incident contact does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    inc.contacts.remove(contact)
    inc.save()
    return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))

@login_required
def remove_handler_incident(request, incident_id, handler_id):
    """remove handler from incident
    """
    context = {}
    try:
        inc = Incident.objects.get(id=incident_id)
    except Incident.DoesNotExist:
        messages.error(request, 'The requested incident does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    try:
        handler = Handler.objects.get(id=handler_id)
    except Handler.DoesNotExist:
        messages.error(request, 'The requested incident handler does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    inc.incident_handler.remove(handler)
    inc.save()
    return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))

@login_required
def add_contact_incident(request, incident_id):
    """add incident contact to incident
    """
    if request.method == 'POST':
        try:
            inc = Incident.objects.get(id=incident_id)
        except Incident.DoesNotExist:
            messages.error(request, 'The requested incident does not exist!')
            return render(request, 'kraut_incident/incident_list.html', context)
        co_dict = slicedict(request.POST, 'ContactCheckBox')
        for key in co_dict:
            co_id = int(co_dict[key])
            try:
                co = Contact.objects.get(id=co_id)
                inc.contacts.add(co)
            except Contact.DoesNotExist:
                messages.error(request, 'Failed getting incident contact with ID: %s' % (co_id))
                return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))
        inc.save()
    return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))

@login_required
def add_handler_incident(request, incident_id):
    """add incident handler to incident
    """
    if request.method == 'POST':
        try:
            inc = Incident.objects.get(id=incident_id)
        except Incident.DoesNotExist:
            messages.error(request, 'The requested incident does not exist!')
            return render(request, 'kraut_incident/incident_list.html', context)
        handler_dict = slicedict(request.POST, 'HandlerCheckBox')
        for key in handler_dict:
            handler_id = int(handler_dict[key])
            try:
                ih = Handler.objects.get(id=handler_id)
                inc.incident_handler.add(ih)
            except Handler.DoesNotExist:
                messages.error(request, 'Failed getting incident handler with ID: %s' % (handler_id))
                return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))
        inc.save()
    return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))

@login_required
def add_task(request, incident_id):
    """add task to incident
    """
    if request.method == 'POST':
        try:
            inc = Incident.objects.get(id=incident_id)
        except Incident.DoesNotExist:
            messages.error(request, 'The requested incident does not exist!')
            return render(request, 'kraut_incident/incident_list.html', context)
        task_dict = slicedict(request.POST, 'TaskCheckBox')
        for key in task_dict:
            task_id = int(task_dict[key])
            try:
                tt = TemplateTask.objects.get(id=task_id)
                template = {
                    "name": tt.name,
                    "description": tt.description
                }
                t = Task(**template)
                t.save()
                inc.tasks.add(t)
            except:
                messages.error(request, 'Failed getting incident task with ID: %s' % (task_id))
                return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))
        messages.info(request, 'Task "%s" added' % (t.name))
        inc.save()
    return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))

@login_required
def update_incident_header(request, incident_id):
    """Update incident header information
    """
    context = {}
    try:
        inc = Incident.objects.get(id=incident_id)
    except Incident.DoesNotExist:
        messages.error(request, 'The requested incident does not exist!')
        return render(request, 'kraut_incident/incident_list.html', context)
    if request.method == "POST":
        inc_title = request.POST.get('incident_title', None)
        inc_severity = request.POST.get('incident_severity', None)
        inc_descr = request.POST.get('incident_description', None)
        if inc_title:
            inc.title = inc_title
        if inc_severity:
            if inc_severity == 'High': inc_severity = 'h'
            if inc_severity == 'Medium': inc_severity = 'm'
            if inc_severity == 'Low': inc_severity = 'l'
            inc.severity = inc_severity
        if inc_descr:
            inc.description = inc_descr
        inc.save()
    return HttpResponseRedirect(reverse("incidents:view_incident", kwargs={'incident_id': incident_id}))

@login_required
def comment_incident(request, incident_id):
    """Add comment to incident
    """
    context = {}
    if request.method == "POST":
        form = IncidentCommentForm(request.POST)
        if form.is_valid():
            try:
                inc = Incident.objects.get(id=incident_id)
            except Incident.DoesNotExist:
                messages.error(request, 'The requested incident does not exist!')
                return render(request, 'kraut_incident/incident_list.html', context)
            data = {
                'ctext': form.cleaned_data['ctext'],
                'author': request.user,
                'incident_reference': inc
            }

kraut_incident/templates/kraut_incident/incident_new.html
{% extends "base.html" %}
{% load staticfiles %}
{% block sidebar %}
{% spaceless %}
<div class="page-header">
    <div class="media">
        <div class="media-left">
            <img src="{{ namespaceicon}}" height="64" class="media-object">
        </div>
        <div class="media-body">
            <h2 class="media-heading">{{ usernamespace }}</h2>Side Panel
        </div>
    </div>
</div>
<div id="create_results"></div> <!-- errors go here -->
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Incident Handler
            <a class="btn btn-primary btn-sm" data-toggle="modal" data-target="#addHandlerModal"><i class="fa fa-user-plus fa-sm"></i> Add Handler</a>
        </h3>
    </div>
    <div class="panel-body">
        <table id="handlers_table" class="table table-condensed table-striped table-bordered" style="font-size: 0.9em;">
            <thead>
                <tr><th>Add</th><th>Lastname</th><th>Firstname</th></tr>
            </thead>
        </table>
    </div>
</div>
<div class="modal bs-example-modal-lg" id="addHandlerModal" tabindex="-1" role="dialog" aria-labelledby="addhandlerlabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="addhandlerlabel">Add Incident Handler</h4>
            </div>
            <form method="post" action="" id="post-handler">
                <div class="modal-body">
                    {% csrf_token %}
                    {% for field in handler_form %}
                        <div class="form-group">
                            {{ field.label_tag }} {{ field }}
                        </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Incident Contacts
            <a class="btn btn-primary btn-sm" data-toggle="modal" data-target="#addContactModal"><i class="fa fa-user-plus fa-sm"></i> Add Contact</a>
        </h3>
    </div>
    <div class="panel-body">
        <table id="contacts_table" class="table table-condensed table-striped table-bordered" style="font-size: 0.9em;">
            <thead>
                <tr><th>Add</th><th>Lastname</th><th>Firstname</th></tr>
            </thead>
        </table>
    </div>
</div>
<div class="modal bs-example-modal-lg" id="addContactModal" tabindex="-1" role="dialog" aria-labelledby="addcontactlabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="addcontactlabel">Add Incident Contact</h4>
            </div>
            <form method="post" action="" id="post-contact">
                <div class="modal-body">
                    {% csrf_token %}
                    {% for field in contact_form %}
                        <div class="form-group">
                            {{ field.label_tag }} {{ field }}
                        </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endspaceless %}
{% endblock %}

{% block content %}
<div class="page-header">
    <div class="media">
        <div class="media-left">
            <img src="{% static 'images/NewIncident.svg' %}" height="64" class="media-object" />
        </div>
        <div class="media-body">
            <h2 class="media-heading">New Incident</h2>create a new incident and record necessary information ...
        </div>
    </div>
</div>
{% if messages %}{% for message in messages %}<div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>{% endfor %}{% endif %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Basic Incident Information</h3>
    </div>
    <div class="panel-body">
        <form method="post" action="" id="post-incident">
            {% csrf_token %}
            {% for field in formset %}
                <div class="form-group">
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Create Incident</button>
        </form>
    </div>
</div>
{% endblock%}

{% block javascript %}
<script type="text/javascript" language="javascript" class="init">
    
// Submit post on submit
$('#post-handler').on('submit', function(event){
    event.preventDefault();
    create_handler_post();
    $('#addHandlerModal').modal('hide')
});

// Submit post on submit
$('#post-contact').on('submit', function(event){
    event.preventDefault();
    create_contact_post();
    $('#addContactModal').modal('hide')
});

// Create Incident Handler Person
function create_handler_post() {
    $.ajax({
        url : "{% url 'incidents:create_handler' %}", // the endpoint
        type : "POST", // http method
        data : { 
            firstname : $('#post_handler_firstname').val(),
            lastname : $('#post_handler_lastname').val(),
            phone : $('#post_handler_phone').val(),
            email : $('#post_handler_email').val(),
            description : $('#post_handler_description').val(),
            'csrfmiddlewaretoken': '{{csrf_token}}',
        },
        // handle a successful response
        success : function(json) {
            $('#post_handler_firstname').val('');
            $('#post_handler_lastname').val('');
            $('#post_handler_phone').val('');
            $('#post_handler_email').val('');
            $('#post_handler_description').val('');
            console.log("success");
            var my_alert = '';
            myObject = JSON.parse(json.message);
            for (var key in myObject) {
                my_alert = my_alert.concat('<div class="alert alert-'+json.result+' alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+key+': '+myObject[key][0]["message"]+'</div>');
            };
            $("#create_results").html(my_alert);
            $('#handlers_table').DataTable().ajax.reload();
        },
        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            $('#create_results').html("<div class='alert alert-danger alert-dismissible' role='alert'>Oops! We have encountered an error: "+errmsg+
                    " <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>");
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
};

// Create Incident Contact Person
function create_contact_post() {
    $.ajax({
        url : "{% url 'incidents:create_contact' %}", // the endpoint
        type : "POST", // http method
        data : { 
            firstname : $('#post_contact_firstname').val(),
            lastname : $('#post_contact_lastname').val(),
            phone : $('#post_contact_phone').val(),
            email : $('#post_contact_email').val(),
            description : $('#post_contact_description').val(),
            'csrfmiddlewaretoken': '{{csrf_token}}',
        },
        // handle a successful response
        success : function(json) {
            $('#post_contact_firstname').val('');
            $('#post_contact_lastname').val('');
            $('#post_contact_phone').val('');
            $('#post_contact_email').val('');
            $('#post_contact_description').val('');
            console.log("success");
            var my_alert = '';
            myObject = JSON.parse(json.message);
            for (var key in myObject) {
                my_alert = my_alert.concat('<div class="alert alert-'+json.result+' alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+key+': '+myObject[key][0]["message"]+'</div>');
            };
            $("#create_results").html(my_alert);
            $('#contacts_table').DataTable().ajax.reload();
        },
        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            $('#create_results').html("<div class='alert alert-danger alert-dismissible' role='alert'>Oops! We have encountered an error: "+errmsg+
                    " <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>");
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
};

$(document).ready( function () {
    var cTable = $('#handlers_table').DataTable({
        processing: true,
        info: false,
        bLengthChange: false,
        serverSide: true,
        oLanguage: {
            sProcessing: "<img src='{% static 'images/loading.gif' %}'>",
        },
        order: [[ 1, "desc" ]],
        ajax: {
            processing: true,
            url: "/api/incident/handlers/",
            dataSrc: "results",
            type: "GET",
            dataType: "json"
        },
        columns: [
            {
                "data": 'id', 
                'sName': 'operations',
                'bSortable': false,
                'aTargets': [ 1 ],
                "mRender": function (data, type, full) {
                    return '<div class="checkbox"><input type="checkbox" id="HandlerCheckBox_'+data+'" form="post-incident" value="'+data+'"></div>'
                }
            },
            {'data': 'lastname', 'sName': 'lastname', 'aTargets': [ 2 ]},
            {'data': 'firstname', 'sName': 'firstname', 'aTargets': [ 3 ]},
        ],
    });
});

$(document).ready( function () {
    var cTable = $('#contacts_table').DataTable({
        processing: true,
        info: false,
        bLengthChange: false,
        serverSide: true,
        oLanguage: {
            sProcessing: "<img src='{% static 'images/loading.gif' %}'>",
        },
        order: [[ 1, "desc" ]],
        ajax: {
            processing: true,
            url: "/api/incident/contacts/",
            dataSrc: "results",
            type: "GET",
            dataType: "json"
        },
        columns: [
            {
                "data": 'id', 
                'sName': 'operations',
                'bSortable': false,
                'aTargets': [ 1 ],
                "mRender": function (data, type, full) {
                    return '<div class="checkbox"><input type="checkbox" id="ContactCheckBox_'+data+'" form="post-incident" value="'+data+'"></div>'
                }
            },
            {'data': 'lastname', 'sName': 'lastname', 'aTargets': [ 2 ]},
            {'data': 'firstname', 'sName': 'firstname', 'aTargets': [ 3 ]},
        ],
    });
});

$('#post-incident').submit(function(){
    $('input[type=checkbox]').each(function () {
        if (this.checked) {
            $('<input />').attr('type', 'hidden')
                .attr('name', this.id)
                .attr('value', this.value)
                .appendTo('#post-incident');
        }
    });
});

</script>
{% endblock %}