kraut_api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from kraut_api import views

urlpatterns = [
    # indicators
    url(r'^indicators/$', views.indicator_list),
    url(r'^indicators/(?P<pk>[0-9]+)/$', views.indicator_detail),
    url(r'^indicators/(?P<pk>[0-9]+)/related/$', views.indicator_detail_related_indicators),
    url(r'^indicators/(?P<pk>[0-9]+)/ttps/$', views.indicator_detail_ttps),
    url(r'^indicators/(?P<pk>[0-9]+)/observables/$', views.indicator_detail_observables),
    url(r'^indicators/(?P<pk>[0-9]+)/compositions/$', views.indicator_detail_compositions),
    # observables
    url(r'^observables/$', views.observable_list),
    url(r'^observables/(?P<pk>[0-9]+)/$', views.observable_detail),
    url(r'^observables/(?P<pk>[0-9]+)/related_objects/$', views.observable_related_objects),
    url(r'^observables/(?P<pk>[0-9]+)/related_packages/$', views.observable_related_packages),
    url(r'^observables/(?P<pk>[0-9]+)/related_indicators/$', views.observable_related_indicators),
    # malware instances
    url(r'^malware_instances/$', views.malware_instances_list),
    # attack pattern
    url(r'^attack_patterns/$', views.attack_patterns_list),
    # campaign
    url(r'^campaigns/$', views.campaign_list),
    url(r'^campaigns/(?P<pk>[0-9]+)/$', views.campaign_detail),
    url(r'^campaigns/(?P<pk>[0-9]+)/related/$', views.campaign_detail_related_indicators),
    url(r'^campaigns/(?P<pk>[0-9]+)/associated/$', views.campaign_detail_associated_campaigns),
    url(r'^campaigns/(?P<pk>[0-9]+)/related_ttps/$', views.campaign_detail_related_ttps),
    url(r'^campaigns/(?P<pk>[0-9]+)/related_packages/$', views.campaign_detail_related_packages),
    # threat actor
    url(r'^threatactors/$', views.threatactor_list),
    url(r'^threatactors/(?P<pk>[0-9]+)/$', views.threatactor_detail),
    url(r'^threatactors/(?P<pk>[0-9]+)/associated/$', views.threatactor_detail_associated_threatactors),
    url(r'^threatactors/(?P<pk>[0-9]+)/campaigns/$', views.threatactor_detail_campaigns),
    url(r'^threatactors/(?P<pk>[0-9]+)/related_packages/$', views.threatactor_detail_related_packages),
    url(r'^threatactors/(?P<pk>[0-9]+)/observed_ttps/$', views.threatactor_detail_observed_ttps),
    # package
    url(r'^packages/$', views.package_list),
    url(r'^packages/(?P<pk>[0-9]+)/$', views.package_detail),
    url(r'^packages/(?P<pk>[0-9]+)/observables/$', views.package_detail_observables),
    url(r'^packages/(?P<pk>[0-9]+)/indicators/$', views.package_detail_indicators),
    url(r'^packages/(?P<pk>[0-9]+)/campaigns/$', views.package_detail_campaigns),
    url(r'^packages/(?P<pk>[0-9]+)/threatactors/$', views.package_detail_threatactors),
    url(r'^packages/(?P<pk>[0-9]+)/ttps/$', views.package_detail_ttps),
    url(r'^packages/(?P<pk>[0-9]+)/quick/(?P<otype>[a-zA-Z]+)/$', views.package_quick, name="package_quick"),
    url(r'^packagesd3/tree/(?P<pk>[0-9]+)/$', views.package_tree),
    # objects
    url(r'^objects/(?P<object_id>[0-9]+)/(?P<object_type>[a-zA-Z0-9]+)/packages/$', views.object_get_packages),
    url(r'^objects/(?P<object_id>[0-9]+)/(?P<object_type>[a-zA-Z0-9]+)/observables/$', views.object_get_observables),
    url(r'^objects/hashes/$', views.object_hash_list),
    url(r'^objects/ips/$', views.object_ip_list),
    url(r'^objects/domains/$', views.object_domain_list),
    url(r'^compositions/(?P<pk>[0-9]+)/$', views.composition_details),
    url(r'^compositions/(?P<pk>[0-9]+)/d3/$', views.composition_details_d3),
    # incident
    url(r'^incident/contacts/$', views.contact_list),
    url(r'^incident/handlers/$', views.handler_list),
    url(r'^incident/tasks/$', views.template_tasks),
    url(r'^incident/(?P<incident_id>[0-9]+)/handlers/$', views.handler_list_incident),
    url(r'^incident/(?P<incident_id>[0-9]+)/contacts/$', views.contact_list_incident),
    url(r'^incidents/$', views.incident_list),
    # ttp
    url(r'^ttps/$', views.ttp_list),
    url(r'^ttp/(?P<pk>[0-9]+)/related_ttps/$', views.ttp_related_ttps),
    url(r'^ttp/(?P<pk>[0-9]+)/related_packages/$', views.ttp_related_packages),
    url(r'^ttp/(?P<pk>[0-9]+)/malware_instances/$', views.ttp_malware_instances),
    url(r'^ttp/(?P<pk>[0-9]+)/attack_patterns/$', views.ttp_attack_patterns),
    # taxii
    url(r'^taxii/feed/information/$', views.taxii_feed_information),
    url(r'^taxii/servers/$', views.taxii_server_list),
    url(r'^taxii/collections/$', views.taxii_collection_list),
    url(r'^comments/(?P<object_type>[a-zA-Z0-9]+)/$', views.list_comments),
]

urlpatterns = format_suffix_patterns(urlpatterns)

kraut_base/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from kraut_base import views

app_name = 'kraut_base'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^incidents/', include(('kraut_incident.urls', 'incidents'), namespace='incidents')),
    url(r'^intel/', include(('kraut_intel.urls', 'intel'), namespace='intel')),
    url(r'^sharing/', include(('kraut_sharing.urls', 'sharing'), namespace='sharing')),
    url(r'^export/', include(('kraut_export.urls', 'export'), namespace='export')),
    url(r'^accounts/', include(('kraut_accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^api/', include(('kraut_api.urls', 'api'), namespace='api')),
    url(r'^api-auth/', include(('rest_framework.urls', 'rest_framework'), namespace='rest_framework')),
    url(r'^search/', include(('kraut_search.urls', 'search'), namespace='search')),
    url(r'^admin/', admin.site.urls),
]

kraut_sharing/urls.py
from django.conf.urls import url
from kraut_sharing import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^poll/$', views.poll, name='poll'),
    url(r'^collections/$', views.list_collections, name='collections'),
    url(r'^collections/(?P<collection_id>\d+)/poll/$', views.poll_now, name='poll_now'),
    url(r'^collections/(?P<collection_id>\d+)/delete/$', views.delete_collection, name='delete_collection'),
    url(r'^servers/$', views.manage_servers, name='servers'),
    url(r'^server/(?P<server_id>\d+)/delete/$', views.delete_server, name='delete_server'),
    url(r'^server/(?P<server_id>\d+)/refresh/$', views.refresh_collection, name='refresh_collection'),
]

kraut_sharing/forms.py
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

from django import forms
from django.forms import ModelForm, widgets

from kraut_sharing.models import TAXII_Remote_Server, TAXII_Remote_Collection

forms.DateInput.input_type="datetime"

class DiscoveryForm(forms.Form):
    url = forms.URLField(label='Discovery URL', max_length='255', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'discoveryURL', 'name': 'discoveryURL'}))


class PollForm(forms.Form):
    url = forms.URLField(label='URL', max_length='255', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'URL'}))
    service = forms.CharField(label='Feed Name', max_length='255', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'feed'}))
    begin_time = forms.DateTimeField(label='Begin timestamp', widget=forms.DateTimeInput(attrs={'class':'form-control', 'id': 'begin'}), required=False)
    end_time = forms.DateTimeField(label='End timestamp', widget=forms.DateTimeInput(attrs={'class':'form-control', 'id': 'end', 'placeholder': 'None'}), required=False)
    poll_choices = (
        ('0', 'only once'),
        ('1', 'every hour'),
        ('8', 'every 8 hours'),
        ('24', 'every 24 hours'),
    )
    poll = forms.ChoiceField(label='Poll periodically', widget=forms.Select(attrs={'class': 'form-control', 'id': 'polling'}), choices=poll_choices)

class AddServerForm(ModelForm):
    class Meta:
        model = TAXII_Remote_Server
        fields = ['name', 'host', 'path', 'port', 'protocol', 'version']
        widgets = {
            'name': widgets.TextInput(attrs={'id': 'post_server_name', 'class': 'form-control', 'placeholder': ''}),
            'host': widgets.TextInput(attrs={'id': 'post_server_host', 'class': 'form-control', 'placeholder': ''}),
            'port': widgets.NumberInput(attrs={'id': 'post_server_port', 'class': 'form-control', 'placeholder': '', 'readonly': True, 'required': True}),
            'path': widgets.TextInput(attrs={'id': 'post_server_path', 'class': 'form-control', 'placeholder': ''}),
            'version': widgets.TextInput(attrs={'id': 'post_server_version', 'class': 'form-control', 'placeholder': '', 'readonly': True, 'required': True}),
            'protocol': widgets.TextInput(attrs={'id': 'post_server_protocol', 'class': 'form-control', 'placeholder': '', 'readonly': True, 'required': True}),
        }

class AddCollectionForm(ModelForm):
    class Meta:
        model = TAXII_Remote_Collection
        fields = ['name', 'begin_timestamp', 'poll_period']
        widgets = {
            'name': widgets.TextInput(attrs={'id': 'post_collection_name', 'class': 'form-control', 'placeholder': ''}),
            'begin_timestamp': widgets.DateTimeInput(attrs={'id': 'post_begin_time', 'class': 'form-control', 'placeholder': ''}),
            'poll_period': widgets.NumberInput(attrs={'id': 'post_poll_period', 'class': 'form-control', 'placeholder': ''}),
        }

class EditCollectionForm(ModelForm):
    class Meta:
        model = TAXII_Remote_Collection
        fields = ['name', 'poll_period']
        widgets = {
            'name': widgets.TextInput(attrs={'id': 'post_collection_name', 'class': 'form-control'}),
            'poll_period': widgets.NumberInput(attrs={'id': 'post_poll_period', 'class': 'form-control'}),
        }

kraut_sharing/views.py
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

import datetime, pytz

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.template import RequestContext
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from kraut_sharing.forms import DiscoveryForm, PollForm, AddServerForm, EditCollectionForm
from kraut_sharing.models import TAXII_Remote_Server, TAXII_Remote_Collection
from kraut_sharing.tasks import refresh_collection_task, poll_collection

# Create your views here.

@login_required
def home(request):
    """ discovery collections available at a TAXII server """
    context = {}
    form = DiscoveryForm()
    context['form'] = form
    context['servers'] = TAXII_Remote_Server.objects.all()
    return render(request, 'kraut_sharing/index.html', context)

@login_required
def manage_osint_feeds(request):
    """ manage OSINT feeds """
    context = {}
    return render(request, 'kraut_sharing/osintfeeds.html', context)


@login_required
def manage_servers(request):
    """ manage taxii servers """
    context = {}
    if not request.method == 'POST':
        serverForm = AddServerForm()
        context['form'] = serverForm
        return render(request, 'kraut_sharing/servers.html', context)
    serverForm = AddServerForm(request.POST)
    if serverForm.is_valid():
        oldID = int(request.POST.get('oldid', 0))
        if oldID == 0:
            new_server = TAXII_Remote_Server.objects.get_or_create(**serverForm.cleaned_data)
            messages.info(request, 'Successfully added new TAXII server!')
        else:
            old_server = TAXII_Remote_Server.objects.filter(id=oldID).update(**serverForm.cleaned_data)
            messages.info(request, 'Successfully updated TAXII server!')
    else:
        if serverForm.errors:
            for field in serverForm:
                for error in field.errors:
                    messages.error(request, '%s: %s' % (field.name, error))
    context['form'] = serverForm
    return HttpResponseRedirect(reverse("sharing:servers"))

@login_required
def delete_server(request, server_id):
    """ delete TAXII server """
    try:
        server = TAXII_Remote_Server.objects.get(pk=int(server_id))
    except TAXII_Remote_Server.DoesNotExist:
        messages.error(request, 'The requested TAXII server does not exist!')
        return HttpResponseRedirect(reverse("sharing:servers"))
    # check for associated collections and delete them as well
    try:
        collections = TAXII_Remote_Collection.objects.filter(server=server)
    except Exception as e:
        print e
        collections = []
    for collection in collections:
        collection.delete()
    # finally delete server
    server.delete()
    messages.info(request, 'The TAXII server was deleted successfully!')
    return HttpResponseRedirect(reverse("sharing:servers"))

@login_required
def list_collections(request):
    """ list all collections """
    context = {}
    if request.method == 'POST':
        oldID = int(request.POST.get('oldid', 0))
        if oldID > 0:
            try:
                collection = TAXII_Remote_Collection.objects.get(id=oldID)
            except TAXII_Remote_Collection.DoesNotExist:
                messages.error(request, "provided collection does not exist!")
                return HttpResponseRedirect(reverse("sharing:collections"))
            collectionForm = EditCollectionForm(request.POST, instance=collection)
            if collectionForm.is_valid():
                collectionForm.save()
                messages.info(request, 'Successfully updated collection!')
            else:
                if collectionForm.errors:
                    for field in collectionForm:
                        for error in field.errors:
                            messages.error(request, '%s: %s' % (field.name, error))
        else:
            messages.error(request, "wrong collection ID provided!")
        return HttpResponseRedirect(reverse("sharing:collections"))
    collectionForm = EditCollectionForm()
    context['form'] = collectionForm
    return render(request, 'kraut_sharing/collections.html', context)

@login_required
def refresh_collection(request, server_id):
    """ refresh list of collections for given server """
    refresh_collection_task(server_id)
    messages.info(request, 'Collection list updated successfully')
    return HttpResponseRedirect(reverse("sharing:servers"))

@login_required
def delete_collection(request, collection_id):
    """ remove given collection from the database """
    try:
        collection = TAXII_Remote_Collection.objects.get(id=collection_id)
    except TAXII_Remote_Collection.DoesNotExist:
        messages.error(request, "provided collection does not exist!")
        return HttpResponseRedirect(reverse("sharing:collections"))
    # TODO: check for subscriptions or poll jobs (cron)
    collname = collection.name
    collection.delete()
    messages.info(request, "collection %s successfully deleted." % (collname))
    return HttpResponseRedirect(reverse("sharing:collections"))

@login_required
def poll_now(request, collection_id):
    """ poll given collection """
    try:
        collection = TAXII_Remote_Collection.objects.get(id=collection_id)
    except TAXII_Remote_Collection.DoesNotExist:
        messages.error(request, "provided collection does not exist!")
        return HttpResponseRedirect(reverse("sharing:collections"))
    try:
        poll_collection.delay(collection)
        messages.info(request, "polling information from: %s ..." % (collection.name))
    except Exception as e:
        messages.error(request, "failed polling collection, check if celery is running")
    return HttpResponseRedirect(reverse("sharing:collections"))

@login_required
def poll(request):
    """ poll collection information """
    context = {}
    # set begin time by default to 24 hours ago
    begin_time = datetime.datetime.now(pytz.utc) - datetime.timedelta(hours = 24)
    if not request.method == 'POST':
        form = PollForm(initial={'begin_time': begin_time.strftime('%Y-%m-%dT%H:%M:%S.%f%z')})
        context['form'] = form
        return render(request, 'kraut_sharing/poll.html', context)
    form = PollForm(initial={'url': request.POST.get('url'), 'service': request.POST.get('service'), 'begin_time': begin_time.strftime('%Y-%m-%dT%H:%M:%S.%f%z')})
    context['form'] = form
    messages.info(request, 'Polling intelligence ...')
    return render(request, 'kraut_sharing/poll.html', context)

kraut_sharing/templates/kraut_sharing/collections.html
{% extends "base.html" %}
{% load staticfiles %}
{% block sidebar %}
{% spaceless %}
<br/>
<br/>
<br/>
{% endspaceless %}
{% endblock %}

{% block content %}
<div class="page-header">
    <div class="media">
        <div class="media-left">
            <img src="{% static 'images/Taxii.svg' %}" height="64" class="media-object" />
        </div>
        <div class="media-body">
            <h2 class="media-heading">Hail a Taxii</h2>manage TAXII collections ...
        </div>
    </div>
</div>
{% if messages %}{% for message in messages %}<div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>{% endfor %}{% endif %}
{% spaceless %}
<br/>
<table id="collection_table" class="table table-condensed table-striped table-bordered" style="font-size: 0.9em;">
    <thead>
        <th>Name</th>
        <th>Subscribed</th>
        <th>Poll Period</th>
        <th>Last Poll</th>
        <th>Operations</th>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>
<div class="modal bs-example-modal-lg" id="editCollectionModal" tabindex="-1" role="dialog" aria-labelledby="editcollectionlabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="editcollectionlabel">Edit Collection</h4>
            </div>
            <form method="post" action="" id="post-collection">
                <div class="modal-body">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }} {{ field }}
                    </div>
                    {% endfor %}
                    <input type="hidden" name="oldid" id="post_collection_oldid" value="0">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endspaceless %}
{% endblock%}

{% block javascript %}
<script src="{% static 'js/bootbox.min.js' %}"></script>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready( function () {
        var sTable = $('#collection_table').DataTable({
            processing: true,
            serverSide: true,
            oLanguage: { 
                sProcessing: "<img src='{% static 'images/loading.gif' %}'>", 
            },
            order: [[ 1, "desc" ]],
            ajax: {
                processing: true,
                url: "/api/taxii/collections/",
                dataSrc: "results", type: "GET", dataType: "json"
            },
            columns: [
                {'data': 'name', 'sName': 'name', 'aTargets': [ 1 ]},
                {
                    'data': 'subscribed', 
                    'sName': 'host', 
                    'aTargets': [ 2 ],
                    "mRender": function (data, type, full) {
                        return '<span class="label label-danger label-pill">'+data+'</span';
                    }
                },
                {'data': 'poll_period', 'sName': 'path', 'aTargets': [ 3 ]},
                {'data': 'last_modified', 'sName': 'last poll', 'aTargets': [ 4 ]},
                {
                    "data": 'id',
                    'sName': 'operations',
                    'bSortable': false,
                    'aTargets': [ 5 ],
                    "mRender": function (data, type, full) {
                        var delete_coll_url = "{% url 'sharing:delete_collection' collection_id=0 %}".replace(0, Number(data));
                        var poll_now_url = "{% url 'sharing:poll_now' collection_id=0 %}".replace(0, Number(data));
                        var return_text = '<div class="btn-group1">'
                        if (full.subscribed) {
                        return_text = return_text +
                            '<a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="Unsubscribe" href="#">' +
                            '<i class="fa fa-close"></i>' +
                            '</a> ';
                        } else {
                        return_text = return_text +
                            '<a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="Subscribe" href="#">' +
                            '<i class="fa fa-check"></i>' +
                            '</a> ';
                        }
                        return_text = return_text +
                            '<a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="Poll Now" href="'+poll_now_url+'">' +
                            '<i class="fa fa-refresh"></i>' +
                            '</a> ';
                        return_text = return_text +
                            '<a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="Edit" onclick="showEdit(\''+full.name+'\', \''+full.poll_period+'\', \''+data+'\')">' +
                            '<i class="fa fa-pencil-square-o"></i>' +
                            '</a>';
                        return_text = return_text +
                            '<a class="btn btn-small confirm" rel="tooltip" data-placement="right" data-original-title="Remove" data-href="'+delete_coll_url+'" data-display="'+full.name+'" href="#">' +
                            '<i class="fa fa-remove"></i>' +
                            '</a> ';
                        return_text = return_text + '</div>';
                        return return_text;
                    },
                    "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                        $("a", nTd).tooltip();
                    }
                }
            ],
        });
    });
    $(document).on("click", ".confirm", function(e) {
        e.preventDefault();
        var title = $(this).attr('data-display');
        var location = $(this).attr('data-href');
        bootbox.confirm('Are you sure?<br/>(Delete: '+title+')', function(confirmed) {
            if(confirmed)
            {
                window.location.replace(location);
            }
        });
    });
    function showEdit(name, period, id) {
        $('#post_collection_name').val(name);
        $('#post_poll_period').val(period);
        $('#post_collection_oldid').val(id);
        $('#editCollectionModal').modal('show');
    }
</script>
{% endblock %}

kraut_sharing/templates/kraut_sharing/servers.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="page-header">
    <div class="media">
        <div class="media-left">
            <img src="{% static 'images/Taxii.svg' %}" height="64" class="media-object" />
        </div>
        <div class="media-body">
            <h2 class="media-heading">Hail a Taxii</h2>manage TAXII servers ...
        </div>
    </div>
</div>
{% if messages %}{% for message in messages %}<div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>{% endfor %}{% endif %}
<br/>
<table id="server_table" class="table table-condensed table-striped table-bordered" style="font-size: 0.9em;">
    <thead>
        <th>Name</th>
        <th>Host</th>
        <th>Path</th>
        <th>Operations</th>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

<a class="btn btn-primary btn-sm" data-toggle="modal" data-target="#addServerModal"><i class="fa fa-server fa-sm"></i> Add Server</a>


<div class="modal bs-example-modal-lg" id="addServerModal" tabindex="-1" role="dialog" aria-labelledby="addserverlabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="addserverlabel">Add TAXII Server</h4>
            </div>
            <form method="post" action="" id="post-server">
                <div class="modal-body">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }} {{ field }}
                    </div>
                    {% endfor %}
                    <input type="hidden" name="oldid" id="post_server_oldid" value="0">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock%}

{% block javascript %}
<script src="{% static 'js/bootbox.min.js' %}"></script>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready( function () {
        var sTable = $('#server_table').DataTable({
            processing: true,
            serverSide: true,
            oLanguage: { 
                sProcessing: "<img src='{% static 'images/loading.gif' %}'>", 
            },
            order: [[ 1, "desc" ]],
            ajax: {
                processing: true,
                url: "/api/taxii/servers/",
                dataSrc: "results", type: "GET", dataType: "json"
            },
            columns: [
                {'data': 'name', 'sName': 'name', 'aTargets': [ 1 ]},
                {'data': 'host', 'sName': 'host', 'aTargets': [ 2 ]},
                {'data': 'path', 'sName': 'path', 'aTargets': [ 3 ]},
                {
                    "data": 'id',
                    'sName': 'operations',
                    'bSortable': false,
                    'aTargets': [ 5 ],
                    "mRender": function (data, type, full) {
                        var delete_url = "{% url 'sharing:delete_server' server_id=0 %}".replace(0, Number(data));
                        var refresh_url = "{% url 'sharing:refresh_collection' server_id=0 %}".replace(0, Number(data));
                        return '<div class="btn-group1">' +
                            '<a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="Refresh Collections" href="'+refresh_url+'">' +
                            '<i class="fa fa-refresh"></i>' +
                            '</a> ' +
                            '<a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="Edit" onclick="showEdit(\''+full.name+'\', \''+full.host+'\', \''+full.path+'\', \''+data+'\')">' +
                            '<i class="fa fa-edit"></i>' +
                            '</a> ' +
                            '<a class="btn btn-small confirm" rel="tooltip" data-placement="bottom" data-original-title="Remove" data-href="'+delete_url+'" data-display="'+full.name+'" href="#">' +
                            '<i class="fa fa-remove"></i>' +
                            '</a>' +
                            '</div>';
                    },
                    "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                        $("a", nTd).tooltip();
                    }
                }
            ],
        });
    });

    $(document).on("click", ".confirm", function(e) {
        e.preventDefault();
        var title = $(this).attr('data-display');
        var location = $(this).attr('data-href');
        bootbox.confirm('Are you sure?<br/>(Delete: '+title+')<br/>This will also delete all associated collections.', function(confirmed) {
            if(confirmed)
            {
                window.location.replace(location);
            }
        });
    });

    function showEdit(name, host, path, id) {
        $('#post_server_name').val(name);
        $('#post_server_host').val(host);
        $('#post_server_path').val(path);
        $('#post_server_oldid').val(id);
        console.log(id)
        $('#addServerModal').modal('show');
    }
</script>
{% endblock %}