kraut_api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from kraut_api import views

urlpatterns = [
    # indicators
    url(r'^indicators/$', views.indicator_list),
    url(r'^indicators/(?P<pk>[0-9]+)/$', views.indicator_detail),
    url(r'^indicators/(?P<pk>[0-9]+)/related/$', views.indicator_detail_related_indicators),
    url(r'^indicators/(?P<pk>[0-9]+)/ttps/$', views.indicator_detail_ttps),
    url(r'^indicators/(?P<pk>[0-9]+)/observables/$', views.indicator_detail_observables),
    url(r'^indicators/(?P<pk>[0-9]+)/compositions/$', views.indicator_detail_compositions),
    # observables
    url(r'^observables/$', views.observable_list),
    url(r'^observables/(?P<pk>[0-9]+)/$', views.observable_detail),
    url(r'^observables/(?P<pk>[0-9]+)/related_objects/$', views.observable_related_objects),
    url(r'^observables/(?P<pk>[0-9]+)/related_packages/$', views.observable_related_packages),
    url(r'^observables/(?P<pk>[0-9]+)/related_indicators/$', views.observable_related_indicators),
    # malware instances
    url(r'^malware_instances/$', views.malware_instances_list),
    # attack pattern
    url(r'^attack_patterns/$', views.attack_patterns_list),
    # campaign
    url(r'^campaigns/$', views.campaign_list),
    url(r'^campaigns/(?P<pk>[0-9]+)/$', views.campaign_detail),
    url(r'^campaigns/(?P<pk>[0-9]+)/related/$', views.campaign_detail_related_indicators),
    url(r'^campaigns/(?P<pk>[0-9]+)/associated/$', views.campaign_detail_associated_campaigns),
    url(r'^campaigns/(?P<pk>[0-9]+)/related_ttps/$', views.campaign_detail_related_ttps),
    url(r'^campaigns/(?P<pk>[0-9]+)/related_packages/$', views.campaign_detail_related_packages),
    # threat actor
    url(r'^threatactors/$', views.threatactor_list),
    url(r'^threatactors/(?P<pk>[0-9]+)/$', views.threatactor_detail),
    url(r'^threatactors/(?P<pk>[0-9]+)/associated/$', views.threatactor_detail_associated_threatactors),
    url(r'^threatactors/(?P<pk>[0-9]+)/campaigns/$', views.threatactor_detail_campaigns),
    url(r'^threatactors/(?P<pk>[0-9]+)/related_packages/$', views.threatactor_detail_related_packages),
    url(r'^threatactors/(?P<pk>[0-9]+)/observed_ttps/$', views.threatactor_detail_observed_ttps),
    # package
    url(r'^packages/$', views.package_list),
    url(r'^packages/(?P<pk>[0-9]+)/$', views.package_detail),
    url(r'^packages/(?P<pk>[0-9]+)/observables/$', views.package_detail_observables),
    url(r'^packages/(?P<pk>[0-9]+)/indicators/$', views.package_detail_indicators),
    url(r'^packages/(?P<pk>[0-9]+)/campaigns/$', views.package_detail_campaigns),
    url(r'^packages/(?P<pk>[0-9]+)/threatactors/$', views.package_detail_threatactors),
    url(r'^packages/(?P<pk>[0-9]+)/ttps/$', views.package_detail_ttps),
    url(r'^packages/(?P<pk>[0-9]+)/quick/(?P<otype>[a-zA-Z]+)/$', views.package_quick, name="package_quick"),
    url(r'^packagesd3/tree/(?P<pk>[0-9]+)/$', views.package_tree),
    # objects
    url(r'^objects/(?P<object_id>[0-9]+)/(?P<object_type>[a-zA-Z0-9]+)/packages/$', views.object_get_packages),
    url(r'^objects/(?P<object_id>[0-9]+)/(?P<object_type>[a-zA-Z0-9]+)/observables/$', views.object_get_observables),
    url(r'^objects/hashes/$', views.object_hash_list),
    url(r'^objects/ips/$', views.object_ip_list),
    url(r'^objects/domains/$', views.object_domain_list),
    url(r'^compositions/(?P<pk>[0-9]+)/$', views.composition_details),
    url(r'^compositions/(?P<pk>[0-9]+)/d3/$', views.composition_details_d3),
    # incident
    url(r'^incident/contacts/$', views.contact_list),
    url(r'^incident/handlers/$', views.handler_list),
    url(r'^incident/tasks/$', views.template_tasks),
    url(r'^incident/(?P<incident_id>[0-9]+)/handlers/$', views.handler_list_incident),
    url(r'^incident/(?P<incident_id>[0-9]+)/contacts/$', views.contact_list_incident),
    url(r'^incidents/$', views.incident_list),
    # ttp
    url(r'^ttps/$', views.ttp_list),
    url(r'^ttp/(?P<pk>[0-9]+)/related_ttps/$', views.ttp_related_ttps),
    url(r'^ttp/(?P<pk>[0-9]+)/related_packages/$', views.ttp_related_packages),
    url(r'^ttp/(?P<pk>[0-9]+)/malware_instances/$', views.ttp_malware_instances),
    url(r'^ttp/(?P<pk>[0-9]+)/attack_patterns/$', views.ttp_attack_patterns),
    # taxii
    url(r'^taxii/feed/information/$', views.taxii_feed_information),
    url(r'^taxii/servers/$', views.taxii_server_list),
    url(r'^taxii/collections/$', views.taxii_collection_list),
    url(r'^comments/(?P<object_type>[a-zA-Z0-9]+)/$', views.list_comments),
]

urlpatterns = format_suffix_patterns(urlpatterns)

kraut_base/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from kraut_base import views

app_name = 'kraut_base'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^incidents/', include(('kraut_incident.urls', 'incidents'), namespace='incidents')),
    url(r'^intel/', include(('kraut_intel.urls', 'intel'), namespace='intel')),
    url(r'^sharing/', include(('kraut_sharing.urls', 'sharing'), namespace='sharing')),
    url(r'^export/', include(('kraut_export.urls', 'export'), namespace='export')),
    url(r'^accounts/', include(('kraut_accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^api/', include(('kraut_api.urls', 'api'), namespace='api')),
    url(r'^api-auth/', include(('rest_framework.urls', 'rest_framework'), namespace='rest_framework')),
    url(r'^search/', include(('kraut_search.urls', 'search'), namespace='search')),
    url(r'^admin/', admin.site.urls),
]

kraut_intel/urls.py
from django.conf.urls import url
from kraut_intel import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    # packages
    url(r'^packages/$', views.packages, name='packages'),
    url(r'^package/(?P<package_id>\d+)/$', views.package, name='package'),
    url(r'^package/(?P<package_id>\d+)/graph/$', views.package_graph, name='package_graph'),
    url(r'^package/(?P<package_id>\d+)/delete/$', views.delete_package, name='delete_package'),
    url(r'^package/(?P<package_id>\d+)/update/header$', views.update_package_header, name='update_package_header'),
    url(r'^package/(?P<package_id>\d+)/edit/$', views.edit_create_package, name='edit_create_package'),
    url(r'^package/(?P<package_id>\d+)/add/(?P<item_id>\d+)/(?P<item_name>\w+)/$', views.add_item_to_package, name='add_item_to_package'),
    url(r'^package/(?P<package_id>\d+)/add/comment$', views.comment_package, name='comment_package'),
    url(r'^package/(?P<package_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_package, name='delete_comment_package'),
    # threat actors
    url(r'^threatactors/$', views.threatactors, name='threatactors'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/$', views.threatactor, name='threatactor'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/delete/$', views.delete_threatactor, name='delete_threatactor'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/edit/$', views.edit_create_threatactor, name='edit_create_threatactor'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/update/header$', views.update_ta_header, name='update_ta_header'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/add/comment$', views.comment_actor, name='comment_actor'),
    url(r'^threatactor/(?P<threat_actor_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_actor, name='delete_comment_actor'),
    # campaigns
    url(r'^campaigns/$', views.campaigns, name='campaigns'),
    url(r'^campaign/(?P<campaign_id>\d+)/$', views.campaign, name='campaign'),
    url(r'^campaign/(?P<campaign_id>\d+)/delete/$', views.delete_campaign, name='delete_campaign'),
    url(r'^campaign/(?P<campaign_id>\d+)/add/comment$', views.comment_campaign, name='comment_campaign'),
    url(r'^campaign/(?P<campaign_id>\d+)/update/header$', views.update_campaign_header, name='update_campaign_header'),
    url(r'^campaign/(?P<campaign_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_campaign, name='delete_comment_campaign'),
    # ttps
    url(r'^ttps/$', views.ttps, name='ttps'),
    url(r'^ttp/(?P<ttp_id>\d+)/$', views.ttp, name='ttp'),
    url(r'^ttp/(?P<ttp_id>\d+)/delete/$', views.delete_ttp, name='delete_ttp'),
    url(r'^ttp/(?P<ttp_id>\d+)/add/comment$', views.comment_ttp, name='comment_ttp'),
    url(r'^ttp/(?P<ttp_id>\d+)/update/header$', views.update_ttp_header, name='update_ttp_header'),
    url(r'^ttp/(?P<ttp_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_ttp, name='delete_comment_ttp'),
    # indicators
    url(r'^indicators/$', views.indicators, name='indicators'),
    url(r'^indicator/(?P<indicator_id>\d+)/$', views.indicator, name='indicator'),
    url(r'^indicator/(?P<indicator_id>\d+)/update/header$', views.update_indicator_header, name='update_indicator_header'),
    url(r'^indicator/(?P<indicator_id>\d+)/delete/$', views.delete_indicator, name='delete_indicator'),
    url(r'^indicator/(?P<indicator_id>\d+)/add/comment$', views.comment_indicator, name='comment_indicator'),
    url(r'^indicator/(?P<indicator_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_indicator, name='delete_comment_indicator'),
    # observables
    url(r'^observables/$', views.observables, name='observables'),
    url(r'^observable/(?P<observable_id>\d+)/$', views.observable, name='observable'),
    url(r'^observable/(?P<observable_id>\d+)/update/header$', views.update_observable_header, name='update_observable_header'),
    url(r'^observable/(?P<observable_id>\d+)/delete/$', views.delete_observable, name='delete_observable'),
    url(r'^observable/(?P<observable_id>\d+)/add/comment$', views.comment_observable, name='comment_observable'),
    url(r'^observable/(?P<observable_id>\d+)/del/comment/(?P<comment_id>\d+)/$', views.delete_comment_observable, name='delete_comment_observable'),
    # malware instance
    url(r'^mwinstances/$', views.malware_instances, name='malware_instances'),
    url(r'^mwinstance/(?P<mwi_id>\d+)/$', views.malware_instance, name='malware_instance'),
    url(r'^mwinstance/(?P<mwi_id>\d+)/delete/$', views.delete_malware_instance, name='delete_malware_instance'),
    url(r'^mwinstance/(?P<mwi_id>\d+)/update/header$', views.update_mwinstance_header, name='update_mwinstance_header'),
    # attack pattern
    url(r'^attpatterns/$', views.attack_patterns, name='attack_patterns'),
    url(r'^attpattern/(?P<ap_id>\d+)/$', views.attack_pattern, name='attack_pattern'),
    url(r'^mwinstance/(?P<ap_id>\d+)/delete/$', views.delete_attack_pattern, name='delete_attack_pattern'),
    url(r'^attpattern/(?P<ap_id>\d+)/update/header$', views.update_attpattern_header, name='update_attpattern_header'),
]

kraut_intel/models.py
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

from django.db import models
from django.contrib.auth.models import User

from kraut_parser.models import Package, ThreatActor, Campaign, TTP, Indicator, Observable

# Create your models here.

class NamespaceIcon(models.Model):
    namespace = models.CharField(max_length=255, unique=True)
    icon = models.CharField(max_length=255)

    def __unicode__(self):
        return u"%s (%s)" % (self.namespace, self.icon)

class PackageComment(models.Model):
    ctext = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)
    package_reference = models.ForeignKey(Package, on_delete=models.CASCADE)


class ThreatActorComment(models.Model):
    ctext = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)
    actor_reference = models.ForeignKey(ThreatActor, on_delete=models.CASCADE)

class CampaignComment(models.Model):
    ctext = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)
    campaign_reference = models.ForeignKey(Campaign, on_delete=models.CASCADE)

class TTPComment(models.Model):
    ctext = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)
    ttp_reference = models.ForeignKey(TTP, on_delete=models.CASCADE)

class IndicatorComment(models.Model):
    ctext = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)
    indicator_reference = models.ForeignKey(Indicator, on_delete=models.CASCADE)

class ObservableComment(models.Model):
    ctext = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)
    observable_reference = models.ForeignKey(Observable, on_delete=models.CASCADE)

kraut_intel/forms.py
from django.forms import ModelForm

from kraut_parser.models import Package, ThreatActor
from kraut_intel.models import PackageComment, ThreatActorComment, CampaignComment, TTPComment, IndicatorComment, ObservableComment

################### PACKAGE #####################

class PackageCommentForm(ModelForm):
    class Meta:
        model = PackageComment
        fields = ['ctext']

    def __init__(self, *args, **kwargs):
        super(PackageCommentForm, self).__init__(*args, **kwargs)
        self.fields['ctext'].widget.attrs.update({'class' : 'form-control', 'id': 'packageComment'})


class PackageForm(ModelForm):
    class Meta:
        model = Package
        fields = ['name', 'description', 'short_description', 'namespace', 'version', 'package_id', 'source', 'produced_time']

    def __init__(self, *args, **kwargs):
        super(PackageForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class' : 'form-control', 'id': 'packageName'})
        self.fields['namespace'].widget.attrs.update({'class' : 'form-control', 'id': 'nameSpace'})
        self.fields['produced_time'].widget.attrs.update({'class' : 'form-control', 'id': 'producedTime'})
        self.fields['version'].widget.attrs.update({'class' : 'form-control', 'id': 'version'})
        self.fields['source'].widget.attrs.update({'class' : 'form-control', 'id': 'source'})
        self.fields['description'].widget.attrs.update({'class' : 'form-control', 'id': 'description'})
        self.fields['short_description'].widget.attrs.update({'class' : 'form-control', 'id': 'shortDescription'})
        self.fields['package_id'].widget.attrs.update({'class' : 'form-control', 'id': 'packageID'})
        self.fields['namespace'].required = True

################### THREAT ACTOR #####################

class ActorCommentForm(ModelForm):
    class Meta:
        model = ThreatActorComment
        fields = ['ctext']

    def __init__(self, *args, **kwargs):
        super(ActorCommentForm, self).__init__(*args, **kwargs)
        self.fields['ctext'].widget.attrs.update({'class' : 'form-control', 'id': 'packageComment'})

class ActorForm(ModelForm):
    class Meta:
        model = ThreatActor
        fields = ['name', 'description', 'short_description', 'namespace', 'threat_actor_id', 'associated_threat_actors']

    def __init__(self, *args, **kwargs):
        super(ActorForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class' : 'form-control', 'id': 'packageName'})
        self.fields['namespace'].widget.attrs.update({'class' : 'form-control', 'id': 'nameSpace'})
        self.fields['description'].widget.attrs.update({'class' : 'form-control', 'id': 'description'})
        self.fields['short_description'].widget.attrs.update({'class' : 'form-control', 'id': 'shortDescription'})
        self.fields['threat_actor_id'].widget.attrs.update({'class' : 'form-control', 'id': 'packageID'})
        self.fields['associated_threat_actors'].widget.attrs.update({'class' : 'form-control', 'id': 'nameSpace'})
        self.fields['namespace'].required = True

################### CAMPAIGN #####################

class CampaignCommentForm(ModelForm):
    class Meta:
        model = CampaignComment
        fields = ['ctext']

    def __init__(self, *args, **kwargs):
        super(CampaignCommentForm, self).__init__(*args, **kwargs)
        self.fields['ctext'].widget.attrs.update({'class' : 'form-control', 'id': 'packageComment'})

################### TTP #####################

class TTPCommentForm(ModelForm):
    class Meta:
        model = TTPComment
        fields = ['ctext']

    def __init__(self, *args, **kwargs):
        super(TTPCommentForm, self).__init__(*args, **kwargs)
        self.fields['ctext'].widget.attrs.update({'class' : 'form-control', 'id': 'packageComment'})

################### INDICATOR #####################

class IndicatorCommentForm(ModelForm):
    class Meta:
        model = IndicatorComment
        fields = ['ctext']

    def __init__(self, *args, **kwargs):
        super(IndicatorCommentForm, self).__init__(*args, **kwargs)
        self.fields['ctext'].widget.attrs.update({'class' : 'form-control', 'id': 'packageComment'})

################### OBSERVABLE #####################

class ObservableCommentForm(ModelForm):
    class Meta:
        model = ObservableComment
        fields = ['ctext']

    def __init__(self, *args, **kwargs):
        super(ObservableCommentForm, self).__init__(*args, **kwargs)
        self.fields['ctext'].widget.attrs.update({'class' : 'form-control', 'id': 'packageComment'})

kraut_intel/templates/kraut_intel/attpattern_details.html
{% extends "base.html" %}
{% load staticfiles %}
{% load split_at %}
{% block header %}
.wrapdiv {
    word-wrap: break-word;         /* All browsers since IE 5.5+ */
    overflow-wrap: break-word;     /* Renamed property in CSS3 draft spec */
    width: 100%;
}
{% endblock %}
{% block sidebar %}
{% spaceless %}
{% if ap %}
<div class="page-header">
    <div class="media">
        <div class="media-left">
            <img src="{{ namespace_icon }}" height="64" class="media-object">
        </div>
        <div class="media-body">
            <h2 class="media-heading">{{ ap.ttp_ref.namespace.last.namespace|split_at:":,0" }}</h2>Side Panel
        </div>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Linked Packages
            <i class="fa fa-question-circle fa-sm" data-container="body" data-toggle="popover" data-placement="right" data-content="List of all packages that reference this TTP entry."></i>
        </h3>
    </div>
    <div id="quick-container" class="panel-body">
        <table id="linked_packages_table" class="table table-condensed table-borderless" style="font-size: 0.9em;">
            <thead>
                <tr><th>Name</th></tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Embedded in TTP
            <i class="fa fa-question-circle fa-sm" data-container="body" data-toggle="popover" data-placement="right" data-content="List of all ttps that are related to the currently viewed ttp."></i>
        </h3>
    </div>
    <div id="quick-container" class="panel-body">
        <table id="related_ttp_table" class="table table-condensed table-borderless" style="font-size: 0.9em;">
            <thead>
                <th>Name</th>
            </thead>
            <tbody>
                <tr>
                    <td><a href="{% url 'intel:ttp' ttp_id=ap.ttp_ref.id %}">{{ ap.ttp_ref.name }}</a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endspaceless %}
{% endblock %}

{% block content %}
<div class="page-header">
    <div class="media">
        <div class="media-left">
            <img src="{% static 'images/Kraut.svg' %}" height="64" class="media-object" />
        </div>
        <div class="media-body">
            <h2 class="media-heading">{{ ap.name }}</h2>Attack Pattern ID: {{ ap_id }}
        </div>
    </div>
</div>
{% if messages %}{% for message in messages %}<div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>{% endfor %}{% endif %}
{% if ap %}
{% spaceless %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">{{ ap.name }} &nbsp;<i id="toggle-navsidebar" class="fa fa-pencil-square-o pull-right" data-toggle="tooltip" data-placement="top" data-original-title="edit meta-information"></i></h3>
    </div>
    <table class="table table-condensed table-borderless">
        <tbody>
            <tr>
                <td align="right"><b>Namespace</b></td>
                <td>{{ ap.ttp_ref.namespace.last.namespace }}</td>
            </tr>
            <tr>
                <td align="right"><b>Import Time</b></td>
                <td>{{ ap.creation_time }}</td>
                <td align="right"><b>Modified Time</b></td>
                <td>{{ ap.last_modified }}</td>
            </tr>
            <tr>
                <td align="right"><b>CAPEC ID</b></td>
                <td>{{ ap.capec_id }}</td>
            </tr>
        </tbody>
    </table>
    <div class="panel-body">
        <pre class="pre-scrollable wrapdiv">{{ description }}</pre>
    </div>
</div>

<div id="navsidebar" class="navsidebar navsidebar-right">
  <div id="navsidebar-wrapper" class="navsidebar-wrapper">
    <header class="navsidebar-header"><i class="fa fa-pencil-square-o"></i>&nbsp;Kraut Editor</header>
    <nav class="navsidebar-menu">
        <form action="{% url 'intel:update_attpattern_header' ap_id=ap_id %}" method="POST">
        {% csrf_token %}
            <ul>
                <li>Title</li>
                <li><input name="ap_name" class="form-control" type="text" value="{{ ap.name }}"></li>
                <li>Capec ID</li>
                <li><input name="ap_capec_id" class="form-control" type="text" value="{{ ap.capec_id }}"></li>
                <li>Description</li>
                <li><textarea name="ap_description" class="form-control" rows="13">{{ ap.description }}</textarea></li>
                <li><button type="submit" class="btn btn-primary close-navsidebar">Submit</button></li>
            </ul>
        </form>
    </nav>
  </div>
</div>

{% endspaceless %}
{% endif %}
{% endblock %}

{% block javascript%}
<script type="text/javascript" language="javascript" class="init">
$(document).ready( function () {
        var pTable = $('#linked_packages_table').DataTable({
            ordering: false,
            paging: false,
            info: false,
            filter: false,
            processing: true,
            serverSide: true,
            oLanguage: {
                sProcessing: "<img src='{% static 'images/loading.gif' %}'>",
                emptyTable: "No related packages found ...",
                sZeroRecords: "No related packages found ...",
                sEmptyTable: "No related packages found ...",
            },
            order: [[ 0, "desc" ]],
            ajax: {
                processing: true,
                url: "/api/ttp/{{ ap.ttp_ref.id }}/related_packages/",
                dataSrc: "results",
                type: "GET",
                dataType: "json"
            },
            columns: [
                {
                    'data': 'name', 
                    'sName': 'name', 
                    'aTargets': [ 1 ],
                    'mRender': function (data, type, full) {
                        var view_url = "{% url 'intel:package' package_id=0 %}".replace(0, Number(full.id));
                        return '<a href="'+view_url+'">'+data+'</a>';
                    }
                }
            ],
        });
});

$(document).ready(function() {
  $('#navsidebar').simplerSidebar({
    opener: '#toggle-navsidebar',
    sidebar: {
      align: 'right', 
      width: 560,
      closingLinks: '.close-navsidebar',
      top: 60,
      animation: {
        duration: 10,
      }
    }
  });
});

</script>
{% endblock%}

kraut_intel/templates/kraut_intel/package_full_tree.html
{% extends "base_single.html" %}
{% load staticfiles %}
{% load split_at %}
{% block header %}
<style>

.node {
  stroke: #fff;
  stroke-width: 1.5px;
}

.link {
  stroke: #999;
  stroke-opacity: .6;
}

</style>
{% endblock %}

{% block content %}
<div class="page-header">
    <div class="media">
        <div class="media-left">
            <img src="{% static 'images/Package.svg' %}" height="64" class="media-object" />
        </div>
        <div class="media-body">
            <h2 class="media-heading">{{ package.name }}</h2>Intelligence Package ID: {{ package_id }}
        </div>
    </div>
</div>
{% if messages %}{% for message in messages %}<div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>{% endfor %}{% endif %}
{% if package %}
{% spaceless %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Package Visualization<a href="{% url 'intel:package' package_id=package_id %}"><i data-toggle="tooltip" data-placement="left" data-original-title="back" class="fa fa-external-link pull-right"></i></a></h3>
    </div>
    <div id="tree-container" class="panel-body">
    </div>
</div>
<input type="hidden" id="package_id" name="variable" value="{{ package_id }}">
{% endspaceless %}
{% endif %}
{% endblock%}

{% block javascript%}
<script type="text/javascript" charset="utf8" src="{% static 'js/package_graph.js' %}"></script>
{% endblock%}